# -*- coding: utf-8 -*-
# SPDX-FileCopyrightText: Contributors to PyPSA-Eur <https://github.com/pypsa/pypsa-eur>
#
# SPDX-License-Identifier: MIT

# This file is used to define the scenarios that are run by snakemake. Each entry on the first level is a scenario. Each scenario can contain configuration overrides with respect to the config/config.yaml settings.
#
# Example
#
# custom-scenario: # name of the scenario
#   electricity:
#       renewable_carriers: [wind, solar] # override the list of renewable carriers

DE_default:

  countries: 
    - DE

  clustering:
    temporal:
      resolution_sector: 3H

FR_default:

  countries: 
    - FR

  clustering:
    temporal:
      resolution_sector: 3H

NO_default:

  countries: ['NO']

  clustering:
    temporal:
      resolution_sector: 3H

#######

ES_default:  
  countries: ['ES']
  clustering:
    mode: administrative
    administrative:
      level: 0
    temporal:
      resolution_sector: 3H
  sector:
    district_heating:
      progress:
        2020: 0.05 # with value of 0 the workflow crashes
        sector:
    co2_sequestration_potential: 50

AT_default:
  countries: ['AT']
  clustering:
    temporal:
      resolution_sector: 3H

DK_default:
  countries: ['DK']
  clustering:
    temporal:
      resolution_sector: 3H

GB_default:
  countries: ['GB']
  clustering:
    mode: administrative
    administrative:
      level: 0
    temporal:
      resolution_sector: 365H
  sector:
    co2_sequestration_potential: 80

IE_default:
  countries: ['IE']
  clustering:
    temporal:
      resolution_sector: 3H

IT_default:
  countries: ['IT']
  clustering:
    temporal:
      resolution_sector: 3H


PL_default:
  countries: ['PL']
  clustering:
    temporal:
      resolution_sector: 3H


SE_default:
  countries: ['SE']
  clustering:
    temporal:
      resolution_sector: 3H

