# -*- coding: utf-8 -*-
# SPDX-FileCopyrightText: Contributors to PyPSA-Eur <https://github.com/pypsa/pypsa-eur>
#
# SPDX-License-Identifier: MIT

# This file is used to define the scenarios that are run by snakemake. Each entry on the first level is a scenario. Each scenario can contain configuration overrides with respect to the config/config.yaml settings.
#
# Example
#
# custom-scenario: # name of the scenario
#   electricity:
#       renewable_carriers: [wind, solar] # override the list of renewable carriers

DE_default:

  countries: 
    - DE

  clustering:
    temporal:
      resolution_sector: 3H

FR_default:

  countries: 
    - FR

  clustering:
    temporal:
      resolution_sector: 3H

NO_default:

  countries: ['NO']

  clustering:
    temporal:
      resolution_sector: 3H

#######

AL_default:
  countries: ['AL']
  clustering:
    temporal:
      resolution_sector: 3H

AT_default:
  countries: ['AT']
  clustering:
    temporal:
      resolution_sector: 3H

BA_default:
  countries: ['BA']
  clustering:
    temporal:
      resolution_sector: 3H

BE_default:
  countries: ['BE']
  clustering:
    temporal:
      resolution_sector: 3H

BG_default:
  countries: ['BG']
  clustering:
    temporal:
      resolution_sector: 3H

CH_default:
  countries: ['CH']
  clustering:
    temporal:
      resolution_sector: 3H

CZ_default:
  countries: ['CZ']
  clustering:
    temporal:
      resolution_sector: 3H


DK_default:
  countries: ['DK']
  clustering:
    temporal:
      resolution_sector: 3H

EE_default:
  countries: ['EE']
  clustering:
    temporal:
      resolution_sector: 3H

ES_default:
  countries: ['ES']
  clustering:
    temporal:
      resolution_sector: 3H

FI_default:
  countries: ['FI']
  clustering:
    temporal:
      resolution_sector: 3H

GB_default:
  countries: ['GB']
  clustering:
    temporal:
      resolution_sector: 3H

GR_default:
  countries: ['GR']
  clustering:
    temporal:
      resolution_sector: 3H

HR_default:
  countries: ['HR']
  clustering:
    temporal:
      resolution_sector: 3H

HU_default:
  countries: ['HU']
  clustering:
    temporal:
      resolution_sector: 3H

IE_default:
  countries: ['IE']
  clustering:
    temporal:
      resolution_sector: 3H

IT_default:
  countries: ['IT']
  clustering:
    temporal:
      resolution_sector: 3H

LT_default:
  countries: ['LT']
  clustering:
    temporal:
      resolution_sector: 3H

LU_default:
  countries: ['LU']
  clustering:
    temporal:
      resolution_sector: 3H

LV_default:
  countries: ['LV']
  clustering:
    temporal:
      resolution_sector: 3H

ME_default:
  countries: ['ME']
  clustering:
    temporal:
      resolution_sector: 3H

MK_default:
  countries: ['MK']
  clustering:
    temporal:
      resolution_sector: 3H

NL_default:
  countries: ['NL']
  clustering:
    temporal:
      resolution_sector: 3H


PL_default:
  countries: ['PL']
  clustering:
    temporal:
      resolution_sector: 3H

PT_default:
  countries: ['PT']
  clustering:
    temporal:
      resolution_sector: 3H

RO_default:
  countries: ['RO']
  clustering:
    temporal:
      resolution_sector: 3H

RS_default:
  countries: ['RS']
  clustering:
    temporal:
      resolution_sector: 3H

SE_default:
  countries: ['SE']
  clustering:
    temporal:
      resolution_sector: 3H

SI_default:
  countries: ['SI']
  clustering:
    temporal:
      resolution_sector: 3H

SK_default:
  countries: ['SK']
  clustering:
    temporal:
      resolution_sector: 3H

XK_default:
  countries: ['XK']
  clustering:
    temporal:
      resolution_sector: 3H
