# -*- coding: utf-8 -*-
# SPDX-FileCopyrightText: Contributors to PyPSA-Eur <https://github.com/pypsa/pypsa-eur>
#
# SPDX-License-Identifier: MIT

# This file is used to define the scenarios that are run by snakemake. Each entry on the first level is a scenario. Each scenario can contain configuration overrides with respect to the config/config.yaml settings.
#
# Example
#
# custom-scenario: # name of the scenario
#   electricity:
#       renewable_carriers: [wind, solar] # override the list of renewable carriers

DE_default:

  countries: 
    - DE

  clustering:
    temporal:
      resolution_sector: 3H

FR_default:

  countries: 
    - FR

  clustering:
    temporal:
      resolution_sector: 3H

FR_365H:

  countries: 
    - FR

  clustering:
    temporal:
      resolution_sector: 365H

NO_default:

  countries: 
    - NO

  clustering:
    temporal:
      resolution_sector: 3H